name: Run Pandoc

on: push
  
env:
  CONTENT: Hello from github workflow

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: mkdir -p public
      - uses: docker://pandoc/core:2.9
        with:
          args: --standalone --output=public/index.html $GITHUB_WORKSPACE/index.md
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: public/
