name: Run Pandoc

on: push
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: mkdir -v -p public
      - run: cp -v cf-logo.jpg public/
      - uses: docker://pandoc/latex:2.9
        with:
          args: --standalone --output=public/index.txt index.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: --standalone --output=public/index.odt index.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: --standalone --output=public/index.epub index.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: --standalone --output=public/index.docx index.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: --standalone --output=public/index.html index.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: --standalone --output=public/index.pdf index.md
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: public/
      - uses: citizen-of-planet-earth/cf-cli-action@master
        with: 
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gds-techarchs
          cf_space: sandbox 
          command: push
