name: Run Pandoc

on: push
  
env:
  CF_API: https://api.london.cloud.service.gov.uk
  CF_ORG: gds-techarchs
  CF_SPACE: sandbox  

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: mkdir -p public
      - run: cp cf-logo.jpg public/
      - uses: docker://pandoc/latex:2.9
        with:
          args: --standalone --output=public/index.html index.md
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: public/
      - uses: citizen-of-planet-earth/cf-cli-action@master
        with: 
          cf_api: $CF_API
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: $CF_ORG
          cf_space: $CF_SPACE 
          command: push
