name: Run Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "$CONTENT - $GITHUB_WORKFLOW - $GITHUB_REPOSITORY" > input.md
        env:
          CONTENT: Hello from github wprkflow
      - uses: docker://pandoc/core:2.9
        with:
          args: --standalone --output=index.html input.md
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: index.html
